### ISSUE TITLE
error: could not register '' database (wrong or NULL argument passed)

### ISSUE THREAD

**Issue by Teemperor** [mikkeloscar/arch-travis#49]
My CI jobs just started failing with this error, see [here](https://travis-ci.org/Teemperor/brave-rewriter-server/jobs/438871049#L455)

**Comment by vufa** [comment]
My CI jobs failed too, config file: [https://github.com/countstarlight/deepin-wine-qq-arch/blob/master/.travis.yml](https://github.com/countstarlight/deepin-wine-qq-arch/blob/master/.travis.yml)
Travis CI log: [https://travis-ci.org/countstarlight/deepin-wine-qq-arch/builds/442520704](https://travis-ci.org/countstarlight/deepin-wine-qq-arch/builds/442520704):
```
$ makepkg
==> Making package: deepin-wine-qq 8.9.6-3 (Wed 17 Oct 2018 06:16:34 AM UTC)
==> Checking runtime dependencies...
error: could not register 'archlinuxfr http://repo.archlinux.fr/$arch' database (wrong or NULL argument passed)
==> Missing dependencies:
  -> p7zip
  -> wine
  -> wine-mono
  -> wine_gecko
  -> xorg-xwininfo
  -> xdotool
  -> wqy-microhei
  -> adobe-source-han-sans-cn-fonts
  -> lib32-alsa-lib
  -> lib32-alsa-plugins
  -> lib32-libpulse
  -> lib32-openal
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies
```
How to solve it? Thank you.

**Comment by FedeDP** [comment]
Any news on this @mikkeloscar ?

**Comment by mikkeloscar** [comment]
Sorry, I have not had any time to look into this. I'll try to look into it next week but are also happy to review PRs :)

**Comment by mikkeloscar** [comment]
This problem should now be fixed by #50. Sorry it took so long for me to look into this :(

**Comment by vufa** [comment]
@mikkeloscar Everything is ok, thank you for your great work:-)

**Comment by remyoudompheng** [comment]
Hello,
I believe this does not fix the case where repos are empty.
When CONFIG_REPOS is empty, the following happens:
```
in read_config():
CONFIG_REPOS=${CONFIG_REPOS//$sep/$'\n'} => CONFIG_REPOS is still empty
...
CONFIG_REPOS=("${CONFIG_REPOS[@]}") => CONFIG_REPOS is now a length 1 array ("")

in add_repositories:
IFS=" " read -r -a splitarr <<< "" => splitarr=()
sed -i "${repo_line}i[${splitarr[0]}]" /etc/pacman.conf => create a "[]" line
sed -i "${repo_line}iServer = ${splitarr[1]}\n" /etc/pacman.conf => create a "Server=" line
```
